-- Script SQL à exécuter APRÈS l'import
-- pour RE-ACTIVER les RLS

ALTER TABLE journees ENABLE ROW LEVEL SECURITY;
ALTER TABLE cigarettes ENABLE ROW LEVEL SECURITY;
ALTER TABLE objectifs ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_notes ENABLE ROW LEVEL SECURITY;
